# Generated by Django 5.1.4 on 2025-02-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Diagnosises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Specializations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('image_path', models.TextField()),
                ('rating', models.IntegerField()),
                ('telephone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=500)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic_app.specialization')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
                'managed': True,
            },
        ),
    ]
