# Generated by Django 5.1.4 on 2025-02-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('producer_country', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('contraindications', models.TextField()),
                ('production_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Medicaments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'В процессе'), (2, 'Завершено')])),
                ('date_appointment', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='Diagnose',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Ожидание подтверждения'), (2, 'Подтверждено'), (3, 'В процессе'), (4, 'Отменено'), (5, 'Перенесено'), (6, 'Завершено')])),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('diagnose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.diagnose')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.procedure')),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic_app.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('type', models.IntegerField(choices=[(1, '3D модель'), (2, 'Рентген')])),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.record')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.doctor')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.procedure')),
            ],
            options={
                'verbose_name_plural': 'Doctors with Procedures',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('doctor', 'procedure'), name='unique_doctor_procedure')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.medicament')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.treatment')),
            ],
            options={
                'verbose_name_plural': 'Treatments with medicaments',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('treatment', 'medicament'), name='unique_medicaments_treatment')],
            },
        ),
    ]
