# Generated by Django 5.1.4 on 2025-03-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelTable(
            name='account',
            table='Accounts',
        ),
        migrations.AlterModelTable(
            name='diagnose',
            table='Diagnoses',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='Doctors',
        ),
        migrations.AlterModelTable(
            name='doctorsprocedures',
            table='DoctorProcedure',
        ),
        migrations.AlterModelTable(
            name='medicament',
            table='Medicaments',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patients',
        ),
        migrations.AlterModelTable(
            name='procedure',
            table='Procedures',
        ),
        migrations.AlterModelTable(
            name='record',
            table='Records',
        ),
        migrations.AlterModelTable(
            name='snapshot',
            table='Snapshots',
        ),
        migrations.AlterModelTable(
            name='specialization',
            table='Specializations',
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='Treatments',
        ),
        migrations.AlterModelTable(
            name='treatmentmedicament',
            table='TreatmentMedicament',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
