# Generated by Django 5.1.4 on 2025-03-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_alter_user_options_alter_account_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='diagnose',
            table='diagnoses',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctors',
        ),
        migrations.AlterModelTable(
            name='doctorsprocedures',
            table='doctorprocedure',
        ),
        migrations.AlterModelTable(
            name='medicament',
            table='medicaments',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='procedure',
            table='procedures',
        ),
        migrations.AlterModelTable(
            name='record',
            table='records',
        ),
        migrations.AlterModelTable(
            name='snapshot',
            table='snapshots',
        ),
        migrations.AlterModelTable(
            name='specialization',
            table='specializations',
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='treatments',
        ),
        migrations.AlterModelTable(
            name='treatmentmedicament',
            table='treatmentmedicament',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
