# Generated by Django 5.1.4 on 2025-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_alter_account_table_alter_diagnose_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
