# Generated by Django 5.1.4 on 2025-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_doctor_telephone_patient_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Телефон'),
        ),
    ]
