# Generated by Django 5.1.4 on 2025-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
