# Generated by Django 5.1.4 on 2025-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0009_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидание подтверждения'), (2, 'Подтверждено'), (3, 'Отменено'), (5, 'Завершено')]),
        ),
    ]
