# Generated by Django 5.1.4 on 2025-03-13 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0010_alter_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='diagnose',
        ),
        migrations.AddField(
            model_name='treatment',
            name='diagnose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.diagnose'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.doctor'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.patient'),
        ),
    ]
