# Generated by Django 5.1.4 on 2025-03-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0011_remove_record_diagnose_treatment_diagnose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидание подтверждения'), (2, 'Подтверждено'), (3, 'Отменено'), (4, 'Завершено')]),
        ),
    ]
