# Generated by Django 5.1.4 on 2025-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0012_alter_record_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='date_appointment',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='treatment',
            name='date_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
